In [42]:
import numpy as np
import time as t
n=5

In [43]:
perm = np.full(n,[0.3,0.5,0.7,0.82,0.9])
perm

array([0.3 , 0.5 , 0.7 , 0.82, 0.9 ])

### There I can change m on any (8;10;12;14;16;18;20) 

In [68]:
def laba(min_m,max_m,xt):
    A = np.random.uniform(size=(min_m,n),low=0,high=4)
    return A,A

In [73]:
rr= laba(9,10,10)
rr

(array([[2.46974592, 2.74360891, 3.32234995, 3.2774141 , 0.07005363],
        [3.90588341, 3.9260829 , 3.35207347, 2.99964884, 2.71806483],
        [1.87836624, 1.77554952, 2.94109208, 3.81436518, 1.67353733],
        [1.48047945, 2.94290267, 1.99483615, 1.55415356, 0.84807593],
        [1.62068525, 2.71630268, 3.93829806, 3.76491941, 1.17501772],
        [0.27308042, 0.51349309, 0.33245925, 3.28421105, 1.66021661],
        [0.47307073, 2.31083842, 0.84733379, 2.96345273, 2.93465517],
        [0.23375983, 3.66533674, 3.68214161, 2.38060695, 2.4476821 ],
        [2.40116784, 1.82412047, 1.5302307 , 3.19325151, 1.27604261]]),
 array([[2.46974592, 2.74360891, 3.32234995, 3.2774141 , 0.07005363],
        [3.90588341, 3.9260829 , 3.35207347, 2.99964884, 2.71806483],
        [1.87836624, 1.77554952, 2.94109208, 3.81436518, 1.67353733],
        [1.48047945, 2.94290267, 1.99483615, 1.55415356, 0.84807593],
        [1.62068525, 2.71630268, 3.93829806, 3.76491941, 1.17501772],
        [0.2730804

In [44]:
m=9

In [45]:
A = np.random.uniform(size=(m,n),low=0,high=4)
A

array([[3.84509807, 2.32992079, 3.44037654, 2.03092403, 0.08842478],
       [2.42797687, 2.75905461, 3.80953655, 1.62314133, 2.79481881],
       [2.13294486, 2.00056106, 0.9798301 , 0.86661927, 3.76823653],
       [1.22998709, 1.95289879, 1.21270056, 1.4576099 , 3.76804654],
       [1.53780806, 1.09459643, 2.22206927, 2.75442715, 2.62562988],
       [3.3204843 , 3.92829809, 0.85730266, 1.04583727, 0.25606946],
       [1.51885539, 1.6783955 , 3.87731733, 3.91569811, 1.78555858],
       [2.08501613, 1.42147734, 2.92661373, 1.5478384 , 0.76627218],
       [3.51264955, 2.85172818, 0.63572656, 3.55487869, 2.86814774]])

In [46]:
Bt = A@perm

In [47]:
Bt

array([6.4716934 , 8.62090877, 6.42808573, 6.78081792, 7.18578627,
       4.64845527, 8.82685167, 5.34374557, 8.42100104])

In [48]:
def E(name_method: str, modul: float)-> float: 
    if name_method == 'normal':
        ep = np.random.normal(0,(modul/1.5))
        if abs(ep)>modul:
            ep =ep*modul/abs(ep)
        return ep
    if name_method == 'rivnomir':
        ep = np.random.uniform(-modul,modul)
        return ep
    if name_method == 'blender':
        ep = E('normal',modul)
        ep=(modul-ep)*ep/abs(ep)
        return ep
    return 0

###  You can put hear anything: modul>0 name_method={'normal','rivnomir'}

In [52]:
Eps = [E('normal',0.035) for i in range(m)]
Eps = np.full(m,Eps)
Eps

array([ 0.01367618, -0.035     , -0.03493674,  0.00861343,  0.02393208,
        0.03003801,  0.00779284, -0.0024429 , -0.03223881])

In [53]:
B = Bt+Eps
B

array([6.48536958, 8.58590877, 6.39314899, 6.78943135, 7.20971835,
       4.67849328, 8.83464451, 5.34130267, 8.38876223])

In [54]:
def MNK(A: np.array,b: np.array)->np.array:
    x=np.linalg.inv(A.T@A)@A.T@b
    return x

In [55]:
def SVDm(A: np.array, b: np.array)->np.array:
    u, s, v = np.linalg.svd(A, full_matrices=True)
    s=1/s
    s=np.c_[s*np.eye(n),np.zeros((n,m-n))]
    return v.T@s@u.T@b

In [56]:
resolution = MNK(A,B)

In [57]:
resolution

array([0.28909366, 0.51177072, 0.70069166, 0.82673469, 0.89042667])

In [58]:
delta = abs((resolution-perm)/perm)

In [59]:
delta

array([0.03635448, 0.02354144, 0.00098808, 0.00821304, 0.01063703])

In [60]:
x=SVDm(A,B)

In [61]:
x

array([0.28909366, 0.51177072, 0.70069166, 0.82673469, 0.89042667])

In [62]:
delta = abs((x-perm)/perm)

In [63]:
delta

array([0.03635448, 0.02354144, 0.00098808, 0.00821304, 0.01063703])