In [1]:
import numpy as np
import os as os
n=5

In [2]:
perm = np.full(n,[0.3,0.5,0.7,0.82,0.9])
perm

array([0.3 , 0.5 , 0.7 , 0.82, 0.9 ])

### There I can change m on any (8;10;12;14;16;18;20) 

In [60]:
m=8

In [64]:
A = np.random.random((m,n))
A

array([[0.95731039, 0.22676013, 0.46847241, 0.07953579, 0.77282309],
       [0.37836817, 0.91571027, 0.76680409, 0.75272739, 0.81962017],
       [0.57443268, 0.86998618, 0.41466603, 0.23436803, 0.97649169],
       [0.36601223, 0.7681511 , 0.21955945, 0.94446903, 0.07702601],
       [0.83436023, 0.95238209, 0.77954177, 0.11508204, 0.91813121],
       [0.37129848, 0.20935444, 0.7028494 , 0.91686138, 0.84492688],
       [0.95871774, 0.30104162, 0.63200501, 0.27049801, 0.51045943],
       [0.63358911, 0.46676665, 0.82119408, 0.45176048, 0.56684832]])

In [63]:
Bt = A@perm

In [46]:
Bt

array([1.35795373, 1.93909588, 1.13979861, 2.32652447, 1.21697888,
       1.55028088, 1.9680705 , 1.80055197, 1.27892876, 1.5152306 ,
       2.31701468, 1.25252076, 1.31324564, 1.16813176, 1.88298018,
       0.63071959, 1.23331197, 1.1984654 , 1.50766679, 0.42606279])

In [47]:
def E(name_method: str, modul: float)-> float:
    if name_method == 'normal':
        ep = np.random.normal(0,(modul/1.5))
        if abs(ep)>modul:
            ep =ep*modul/abs(ep)
        return ep
    if name_method == 'rivnomir':
        ep = np.random.uniform(-modul,modul)
        return ep
    return 0

###  You can put hear anything: modul>0 name_method={'normal','rivnomir'}

In [48]:
Eps = np.full(m,[E('normal',0.05)])
Eps

array([-0.03258661, -0.03258661, -0.03258661, -0.03258661, -0.03258661,
       -0.03258661, -0.03258661, -0.03258661, -0.03258661, -0.03258661,
       -0.03258661, -0.03258661, -0.03258661, -0.03258661, -0.03258661,
       -0.03258661, -0.03258661, -0.03258661, -0.03258661, -0.03258661])

In [49]:
B = Bt+Eps
B

array([1.32536713, 1.90650928, 1.10721201, 2.29393786, 1.18439228,
       1.51769427, 1.93548389, 1.76796536, 1.24634215, 1.482644  ,
       2.28442807, 1.21993416, 1.28065903, 1.13554516, 1.85039357,
       0.59813298, 1.20072537, 1.16587879, 1.47508019, 0.39347618])

In [50]:
def MNK(A: np.array,b: np.array)->np.array:
    x=np.linalg.inv(A.T@A)@A.T@b
    return x

In [51]:
def SVDm(A: np.array, b: np.array)->np.array:
    u, s, v = np.linalg.svd(A, full_matrices=True)
    s=1/s
    s=np.c_[s*np.eye(n),np.zeros((n,m-n))]
    return v.T@s@u.T@b

In [52]:
resolution = MNK(A,B)

In [53]:
resolution

array([0.28043307, 0.49013688, 0.68811948, 0.80391645, 0.89133776])

In [54]:
delta = abs((resolution-perm)/perm)

In [55]:
delta

array([0.0652231 , 0.01972624, 0.01697217, 0.01961409, 0.00962471])

In [56]:
x=SVDm(A,B)

In [57]:
x

array([0.28043307, 0.49013688, 0.68811948, 0.80391645, 0.89133776])

In [58]:
delta = abs((x-perm)/perm)

In [59]:
delta

array([0.0652231 , 0.01972624, 0.01697217, 0.01961409, 0.00962471])